# Generated by Django 5.2.7 on 2025-10-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOVIES',
            fields=[
                ('MOVIE_id', models.IntegerField(primary_key=True, serialize=False)),
                ('MOVIE_name', models.CharField(max_length=50)),
                ('MOVIE_AMOUNT', models.CharField(max_length=50)),
                ('MOVIE_SCREEN', models.IntegerField()),
                ('MOVIE_DATE', models.DateField()),
            ],
        ),
    ]
